DB_USER: ENC[AES256_GCM,data:knRo,iv:Mt9dIxqEBWFiRoPp9AVojHSktkSVhuWOz7QwOFmjzPI=,tag:fWjx8Lp7yST3ploNbOIGLA==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:q0fTt6yEYVLoxh4eTH0DREOnRzy2UA8+ONqAT9g=,iv:lqDBQ7XL20pFlirNYAdxZj2G4VO0RChYOz5kqe5bvWM=,tag:VEt/rscoOnAArs95DGeTdg==,type:str]
DB_NAME: ENC[AES256_GCM,data:P4BP5T5tmOG1D1I+YZ7E,iv:6oGfDEJWhzG3gQ29/anMuGFaR3dAC1djX0GqDnQJMDQ=,tag:dcXdz6+3iBQKFd/dhW8lJQ==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:312O2AKjqlVIqKq9dMRxR5IIrpq9ccGbFOnPkN9nGVNxKN5N8z5L6R8YSxvjZ7BqIBTfUpCeZmyb6jBMnX+KO4Ox2VxpCPRs+5jSZKpPAO4yaiWr,iv:Vp9xH9qRc4Z23n9E6dYP8dbohLLzwOpWw0fpsQF4oOg=,tag:wtnj4W5xVi2hwHIAuTTQnw==,type:str]
INTERNAL_API_KEY: ENC[AES256_GCM,data:6vmD3AGtDmkL7j5OkxEF03pNd+HTfHBZn8B41hk=,iv:bkHt3B4M55Y8gDkd1BOVbtZCooEhR+Zs0tnzaC/q5+g=,tag:g8SAzXxhvTXl1SY7VoI3Ww==,type:str]
REGISTRAR_IMAGE: ENC[AES256_GCM,data:3W+nrtwm4lyi6ZBZqpkUI3hwFE83oet05xc9XDHtuL88LR2pNpGdDUfv89YPjBXGH+Jfczqq,iv:msqtqMw4nCwH95HG30Do2HgXs70eCEaDzPqFC0nzo5M=,tag:YGEA0zfU6Ug/jKXKOHc0dQ==,type:str]
MAIL_SERVICE_IMAGE: ENC[AES256_GCM,data:hClLd8HcLWWDp0wIsEauoRhsHoA4J3/cZNRgJThcdwWeTthMrXSzV71KxVsdL8WrMl0EqBr56ikh,iv:uuqKkDpNgh9AmPa5Xgt03Afi0CiMBEBh3+0YZi1reS4=,tag:e1x9kqkD3BZYPqOr+cvw5Q==,type:str]
AA_PROXY_IMAGE: ENC[AES256_GCM,data:eEDqj9O+7RDuLZK0yJxZvnEXXKNzLgUufiGAgfIAee3ZChmO2adAgYZBtirQHS8T/wLsCqo=,iv:wphu+s4pmP1wgOjTE2iBNH3QW+jYkDsxkiEOjvURIfU=,tag:cgWSsK7+yCpT9W3JKoc0vg==,type:str]
TTS_PROXY_IMAGE: ENC[AES256_GCM,data:DVIbcaEGCguKjJvxfD9Y7TekHpLZ6cNqssZHVfEmdPc7QzTYJaH4MewVpe8gDwvq4YVvY4ci,iv:MlP1HVMWRLK+II3YI9c4i81XvqE/EKIP0LuE2Fl24+k=,tag:Tbh492mGjcHqp7OMPGqdfA==,type:str]
DESKTOP_UI_IMAGE: ENC[AES256_GCM,data:yQALbnJHR1qyJyU/ilzQ6SbzcN9cEvHdLK6bFgHHmmXk+SB6BBxilxxJ947GjsDNtcNKxLXwXQ==,iv:wFeGt3oTRJ+fn6K5I2i0WxrgNc2pjoCGnmEq9hrX4Ks=,tag:BpWymD9L+JquPG64zhnYIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wyhed2l5j3p5n6gvczpud7upztgu999jdrnhvs9nscdp8m7m9glse4ju0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaE10TWtxdWsvODF6NTAv
            MnZGWWJZUGsxdVVGWXl2WnhoSVZQZVhtSWpvCnNLR1pCbyt0dm02U1czRXlYQTF6
            dVRUczFHY0hna3hnb2pnenNYRVc5RzQKLS0tIEY4UWZiWGltNU01SmVsS3JXYWJV
            OG9xMFhacFBVWHdjUVgrcnJZRysvYWcKtYesIX/oQ5xr9aWDdAIzKRxGoZh7GIRC
            LaOF3TlB6hXXHuULRSJdgmxUsWqpH3c30LKbhNAEF+V2rRfWimPTyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T16:36:53Z"
    mac: ENC[AES256_GCM,data:7RtJjojKO+E9IXlAyI7XpbsY9NFfCG4LKOcQ8+YsuJrTAMISiGl4++rkMC8U4SBn8t5GOeePwTh57ZNXg4jfGJgu0Twhl86lGNPN3sLuZw2d0JOhfvVTk23yje5RPDNG7aLJKMFv+AoYKBpP873aurkDQlC1gqfXx0TryV+IGpc=,iv:0hUpgd4q/SZ/yYmCylCZFPc5vSFhRib3M2XTwN645Yo=,tag:6xko2gPqMKUE1OHEMNniFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
