DB_USER: ENC[AES256_GCM,data:vpes,iv:x9h02CVbJP5LznEcJJ+YS8J7GJvzMcI7fwsAojRoyzc=,tag:nr6S0FYm6YIDE7EfWySlRg==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:hnwjZwl1dcZ1KRoYOLVj/SxJG5NmApXo65qkoOk=,iv:cOcFn29uCBVGeS5EyQeAOVN0EgCf0AixKuSdo0WJGVk=,tag:s+LGU2i6tXL7w00pVOKGpQ==,type:str]
DB_NAME: ENC[AES256_GCM,data:gEpUlKEcJ+qm504XJSz6,iv:Xe3qTISmnmjML63QhZ6MtaG1IfhtJT3aydtikX8azQE=,tag:ki1xkkp4+vrNvypBd8aYXw==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:4Bn8eHZgx5Z++T7jq0uLrXDvvQKdF02Mn7Gkg1CI7IvyhnBJJNQLG9F/Cq6L1NoN7XZD+q33pNXjKwe+4Gusnbl6FLj+Kt6NfV6ME9zpNzSjFWFS,iv:fZ/hodhEialVfbzeDPPxtU8EboKqrJj9Bwx04M1CVQg=,tag:XuYfJxYPjOnlRnbaTzSKng==,type:str]
INTERNAL_API_KEY: ENC[AES256_GCM,data:pWuiF9WI9Qt6MruvMrmaTuuPP5Hp2Zb6zE1dYQs=,iv:03NsXT8mrET9MPS46CMm+TWdVNiwRpEkALHemxokP9A=,tag:YEmLvDYBgZ55XE4bHcmi6A==,type:str]
REGISTRAR_IMAGE: ENC[AES256_GCM,data:GXz4ev0jfy+QL5GgzlsBM3YoMazvV+FBWEmqT7D5L+aE7kkzvTNJW0ZxOQjbHcvCbk7cDOL+,iv:RpZbJA06RLrldiL4r5jaMc0IvyDOUFkK5OMvsOLhS7U=,tag:Xu2dS6T/OJvcUeNAQ4LXMg==,type:str]
MAIL_SERVICE_IMAGE: ENC[AES256_GCM,data:cNEtKBgtzv0nKx9FgbU0RNR/AH99daYvFsm7OJBEt9FSnAFGVwXsaVEyplfUUKitfD3JaZwz1GBe,iv:ewYsc/uPqq3lAYQSpsfj9uZbChZ9WQ2435XQA0XlhEs=,tag:B/VMTDd5sG+t6tvpS7zvuA==,type:str]
AA_PROXY_IMAGE: ENC[AES256_GCM,data:t0/NgAEqHHY5ChJKXZBdH49HfeyElUV0y1G+YZ2Vxz2iHu3MXTGoN7JwA/hmKlYB8ycPQiY=,iv:awSnf8vRt/HsxOd/DzBwSk6tsHPWhN5E4KPgurY6Ypw=,tag:6idIoG3++itWqa7SSegtTg==,type:str]
TTS_PROXY_IMAGE: ENC[AES256_GCM,data:nkqZmWsnhj1541tqbMmPkugiwxOaJBGiZZkieY9wCctdpTi8/wW23kpQcpkxeMC6bUQyu/Ty,iv:modXeMWp6VV1G+GpeI766LwSq+rJF4Uyc5+TvFl/bz8=,tag:cutDXIpky3xBmcwkwG4MSA==,type:str]
DESKTOP_UI_IMAGE: ENC[AES256_GCM,data:J/LxOcRXxW5FTspz0hkam0pDlabL53nPECdeLkBiQpP8OwvzE1bO/VPMcOuWC+0LzfTp5v6LEA==,iv:oJ55W7sffraNE6Lp9PAA8mcNY0/r7V1E8TTNDF1tyO0=,tag:oV+7ydPa3+qaO1PZH27PIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wyhed2l5j3p5n6gvczpud7upztgu999jdrnhvs9nscdp8m7m9glse4ju0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYUxJN2g2N2poRTZ5QVdh
            eW5WcHlBcCtzUDd0N25XeHJsdzliY3dSbkRzCkxqbU5vL2pXSmVNTGZqVktRenpD
            L3JjYW1LNjhjM0lyRmlNYk9nd2lUQmMKLS0tIEFYekNIYmV5ZC9ldWRtbnEvcUV1
            SU1maHdLOVNqbmJvNnp4OWlRNTErTHcKEGngSOOo2ayX1BrAbEIVelsUmxgz+EWD
            B0EqK4LWKAtxPxuM3O4V9b/19w1wdTx43YU/Bn4PnhVRZi3A+mLo9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T16:36:52Z"
    mac: ENC[AES256_GCM,data:l4KAiaiDwxHRsYpGpNaw3VWUK23S0GXZ7rPhSOnNNAEZS7oBHIN+MbEg2cuDWRMyk/uwWkG1d/0hAqOEJbzpfOV7NFf+fi232+O0SNbK+YV9rRasVQX6iIMKsJSxh1iODReai/BdgvMWPfbFUa0uQEZlzhc92Vr8XyfyBA5agrE=,iv:ttqGeWDLQIEzsnRnv1i0009iBieXEnrDu1sGz8lbXzU=,tag:/AHFBWLVmWRxxGWw9SIPbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
